import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}"
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {

      fontFamily: {
        sans: ["Lato", "sans-serif"],
        carmax: ["Carmax Variable", "sans-serif"],
      },

      colors: {
        brand: "var(--color-primary-green)",
        brand2: "var(--color-primary-green2)",
        "brand-green": {
          DEFAULT: "var(--color-primary-green)",
          light: "var(--color-primary-green-light)",
          medium: "var(--color-primary-green-medium)",
          dark: "var(--color-primary-green-dark)",
          alt: "var(--color-primary-green-alt)",
          alpha: "var(--color-primary-green-alpha)",
          foreground: "hsl(0 0% 100%)",
        },
        "hero-bg": "var(--color-background-hero-blue)",
        "light-blue": "var(--color-background-light-blue)",
        "review-blue": "var(--color-background-review-blue)",
        "prequalify-blue": "var(--color-background-prequalify-blue)",
        "light-gray": "var(--color-neutral-light-gray)",
        "light-gray2": "var(--color-neutral-light-gray2)",
        "border-gray": "var(--color-border-light)",
        "dark-gray": "var(--color-neutral-dark-gray)",
        "sold-overlay": "var(--color-special-sold)",
        "price-green": "var(--color-special-price)",
        "review-avatar": "var(--color-special-avatar)",
        star: "var(--color-special-star)",
        "star-amber": "var(--color-special-star-amber)",
        "avatar-purple": "var(--color-special-avatar-purple)",

        border: {
          DEFAULT: "var(--color-border-system)",
          light: "var(--color-border-light)",
          lightGray: "var(--color-border-light-gray)",
          standard: "var(--color-border-standard)",
          darkCharcoal: "var(--color-border-dark-charcoal)",
          dark: "hsl(217.2 32.6% 17.5%)",
        },
        input: {
          DEFAULT: "hsl(214.3 31.8% 91.4%)",
          dark: "hsl(217.2 32.6% 17.5%)",
          text: "var(--color-special-input-text)",
        },
        ring: {
          DEFAULT: "hsl(222.2 84% 4.9%)",
          dark: "hsl(212.7 26.8% 83.9%)",
        },
        background: {
          DEFAULT: "var(--color-background-primary)",
          secondary: "var(--color-background-secondary)",
          light: "var(--color-background-light)",
          heroBlue: "var(--color-background-hero-blue)",
          lightBlue: "var(--color-background-light-blue)",
          prequalifyBlue: "var(--color-background-prequalify-blue)",
          reviewBlue: "var(--color-background-review-blue)",
          greenCard: "var(--color-background-green-card)",
          greenTrack: "var(--color-background-green-track)",
          lightBeige: "var(--color-background-light-beige)",
          darkBg: "var(--color-background-dark-bg)",
          darkCard: "var(--color-background-dark-card)",
          dark: "hsl(222.2 84% 4.9%)",
        },
        foreground: {
          DEFAULT: "hsl(0 0% 0%)",
          dark: "hsl(210 40% 98%)",
        },
        primary: {
          DEFAULT: "var(--color-primary-green)",
          green: "var(--color-primary-green)",
          greenLight: "var(--color-primary-green-light)",
          greenMedium: "var(--color-primary-green-medium)",
          greenDark: "var(--color-primary-green-dark)",
          green2: "var(--color-primary-green2)",
          green3: "var(--color-primary-green3)",
          greenAlt: "var(--color-primary-green-alt)",
          greenAlpha: "var(--color-primary-green-alpha)",
          foreground: "hsl(0 0% 100%)",
          dark: "hsl(210 40% 98%)",
          "dark-foreground": "hsl(222.2 47.4% 11.2%)",
        },
        neutral: {
          white: "var(--color-neutral-white)",
          offWhite: "var(--color-neutral-off-white)",
          lightGray: "var(--color-neutral-light-gray)",
          lightGray2: "var(--color-neutral-light-gray2)",
          mediumGray: "var(--color-neutral-medium-gray)",
          mediumGray2: "var(--color-neutral-medium-gray2)",
          mediumGray3: "var(--color-neutral-medium-gray3)",
          mediumDarkGray: "var(--color-neutral-medium-dark-gray)",
          darkGray: "var(--color-neutral-dark-gray)",
          darkGray2: "var(--color-neutral-dark-gray2)",
          darkGray3: "var(--color-neutral-dark-gray3)",
          darkGray4: "var(--color-neutral-dark-gray4)",
          charcoal: "var(--color-neutral-charcoal)",
        },
        secondary: {
          DEFAULT: "hsl(210 40% 96.1%)",
          foreground: "hsl(222.2 47.4% 11.2%)",
          dark: "hsl(217.2 32.6% 17.5%)",
          "dark-foreground": "hsl(210 40% 98%)",
        },
        destructive: {
          DEFAULT: "var(--color-semantic-error)",
          foreground: "hsl(210 40% 98%)",
          dark: "var(--color-semantic-error-dark)",
          "dark-foreground": "hsl(210 40% 98%)",
        },
        muted: {
          DEFAULT: "hsl(210 40% 96.1%)",
          foreground: "var(--color-text-muted)",
          dark: "hsl(217.2 32.6% 17.5%)",
          "dark-foreground": "hsl(215 20.2% 65.1%)",
        },
        accent: {
          DEFAULT: "var(--color-special-accent)",
          foreground: "hsl(222.2 47.4% 11.2%)",
          dark: "hsl(217.2 32.6% 17.5%)",
          "dark-foreground": "hsl(210 40% 98%)",
        },
        popover: {
          DEFAULT: "hsl(0 0% 100%)",
          foreground: "hsl(222.2 84% 4.9%)",
          dark: "hsl(222.2 84% 4.9%)",
          "dark-foreground": "hsl(210 40% 98%)",
        },
        card: {
          DEFAULT: "hsl(0 0% 100%)",
          foreground: "hsl(222.2 84% 4.9%)",
          dark: "hsl(222.2 84% 4.9%)",
          "dark-foreground": "hsl(210 40% 98%)",
        },
        "search-panel": "hsl(165 35% 75%)",
        "result-bg": "hsl(200 75% 92%)",
        "review-bg": "var(--color-background-review-blue)",
        "diff-card": "hsl(210 100% 97%)",
        "review-name": "hsl(220 70% 25%)",
        "dark-section": {
          DEFAULT: "var(--color-background-dark-bg)",
          foreground: "hsl(0 0% 100%)",
        },
        "dark-card": "var(--color-background-dark-card)",
        "dark-border": "hsl(0 0% 18%)",
        sidebar: {
          DEFAULT: "hsl(0 0% 98%)",
          foreground: "hsl(240 5.3% 26.1%)",
          primary: "hsl(240 5.9% 10%)",
          "primary-foreground": "hsl(0 0% 98%)",
          accent: "hsl(240 4.8% 95.9%)",
          "accent-foreground": "hsl(240 5.9% 10%)",
          border: "hsl(220 13% 91%)",
          ring: "hsl(217.2 91.2% 59.8%)",
          dark: "hsl(240 5.9% 10%)",
          "dark-foreground": "hsl(240 4.8% 95.9%)",
          "dark-primary": "hsl(224.3 76.3% 48%)",
          "dark-primary-foreground": "hsl(0 0% 100%)",
          "dark-accent": "hsl(240 3.7% 15.9%)",
          "dark-accent-foreground": "hsl(240 4.8% 95.9%)",
          "dark-border": "hsl(240 3.7% 15.9%)",
          "dark-ring": "hsl(217.2 91.2% 59.8%)",
        },
      },

      backgroundImage: {
        "brand-gradient": "linear-gradient(to bottom, var(--color-primary-green-alpha), var(--color-primary-green))",
        "brand-gradient-reverse": "linear-gradient(to top, var(--color-primary-green-alpha), var(--color-primary-green))",
        "brand-btn-gradient": "linear-gradient(to bottom, var(--color-primary-green), var(--color-primary-green-alpha))",
        "trade-gradient": "linear-gradient(180deg, var(--color-background-green-gradient-start), var(--color-background-green-gradient-mid), var(--color-background-green-gradient-end))",
        "trade-card-gradient": "linear-gradient(180deg, var(--color-background-green-gradient-start) 0%, var(--color-background-green-card) 100%)",
      },

      borderRadius: {
        lg: "0.5rem",
        md: "calc(0.5rem - 2px)",
        sm: "calc(0.5rem - 4px)",
      },

      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },

      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;