import { AppConfig } from "@/lib/appConfig";
import type { UiState } from "instantsearch.js";

type PlainObject = Record<string, any>;

const MODEL_TO_MAKE = new Map<string, string>();

export function setModelMakeMap(entries: Iterable<[string, string]>) {
  for (const [model, make] of entries) {
    MODEL_TO_MAKE.set(model, make);
  }
}

export function getModelMakeMap() {
  return MODEL_TO_MAKE;
}
 
export const FILTER_KEYS: Record<string, string> = {
  location: "locations",
  vehicle_type: "vehicleTypes",
  year: "year",
  make: "makes",
  model: "models",
  exterior_color: "colors",
  body_type: "bodyStyles",
  transmission: "transmissions",
  fuel_type: "fuelTypes",
};
 
export const modelMakeAssociations = new Map<string, string>();

export type MakeModelSelection = { make: string; model: string };

export function parseMakeModelSelections(value: string): MakeModelSelection[] {
  return value.split(",").filter(Boolean).flatMap((entry) => {
    const separator = entry.indexOf(";");
    if (separator < 1 || separator === entry.length - 1) return [];
    return [{ make: entry.slice(0, separator), model: entry.slice(separator + 1) }];
  });
}

let activeRouterResync: (() => void) | null = null;

export function resyncInventoryUrl() {
  activeRouterResync?.();
}

export const RANGE_KEYS: Record<string, readonly [string, string]> = {
  selling_price: ["priceLow", "priceHigh"],
  odometer: ["odometerLow", "odometerHigh"],
};

 
const PUBLIC_SORT_FIELDS: Record<string, string> = {
  selling_price: "price",
};

function getPublicSort(sortBy: unknown) {
  if (typeof sortBy !== "string") return null;

  const sortExpression = sortBy.split("/sort/")[1];
  if (!sortExpression) return null;
 
  const criteria = sortExpression.split(",");
  const primaryCriterion = criteria.find((c) => !c.startsWith("status_rank:")) || criteria[0];
  const [field, direction] = primaryCriterion.split(":", 2);
  if (!field || !direction) return null;

  return {
    field: PUBLIC_SORT_FIELDS[field] || field,
    direction: direction.toUpperCase(),
  };
}

function getInternalSortField(field: string) {
  return Object.entries(PUBLIC_SORT_FIELDS).find(([, publicField]) => publicField === field)?.[0] || field;
}

let isInternalUrlWrite = false;
let historyPatched = false;
const externalUrlListeners = new Set<() => void>();

function watchExternalUrlChanges() {
  if (historyPatched || typeof window === "undefined") return;
  historyPatched = true;

  const originalPushState = window.history.pushState.bind(window.history);
  const originalReplaceState = window.history.replaceState.bind(window.history);
  const notify = () => externalUrlListeners.forEach((listener) => listener());

  window.history.pushState = function (...args: Parameters<typeof originalPushState>) {
    const result = originalPushState(...args);
    if (!isInternalUrlWrite) notify();
    return result;
  };
  window.history.replaceState = function (...args: Parameters<typeof originalReplaceState>) {
    const result = originalReplaceState(...args);
    if (!isInternalUrlWrite) notify();
    return result;
  };
  window.addEventListener("popstate", notify);
}

const FILTER_ATTRIBUTES = Object.keys(FILTER_KEYS);
const PATH_ATTRIBUTES = [
  "year",
  "make",
  "model",
  "body_type",
  "vehicle_type",
  "exterior_color",
  "fuel_type",
  "location",
] as const;
type PathFilters = Partial<Record<(typeof PATH_ATTRIBUTES)[number], string[]>>;

function isInventoryListingPath(pathname: string) {
  const segments = pathname.replace(/^\/inventory\/?/, "").split("/").filter(Boolean);
  if (!segments.length) return pathname === "/inventory" || pathname === "/inventory/";

  // Vehicle detail links begin with an inventory ID (for example 3019-...);
  // listing paths may begin with a four-digit vehicle year.
  const firstToken = segments[0].split("-", 1)[0];
  const numericValue = Number(firstToken);
  return !/^\d+$/.test(firstToken) || (numericValue >= 1900 && numericValue <= 2100);
}

const titleCase = (value: string) => value
  .split("-")
  .filter(Boolean)
  .map((part) => {
    const acronyms: Record<string, string> = { bmw: "BMW", gmc: "GMC", ram: "RAM", suv: "SUV" };
    return acronyms[part.toLowerCase()] || `${part.charAt(0).toUpperCase()}${part.slice(1)}`;
  })
  .join(" ");

function readPathOnlyFilters(segments: string[], refinementList: PlainObject) {
  const set = (attribute: keyof PathFilters, value: string) => {
    if (!value || refinementList[attribute]) return;
    // Tolerate comma-separated values here too, so links generated by the old buggy
    // serializer (which crammed multiple selections into one path segment) still parse
    // instead of silently failing.
    const values = value.split(",").filter(Boolean).map(titleCase);
    if (values.length) refinementList[attribute] = values;
  };
  const [vehicleSegment, detailSegment] = segments.map(decodeURIComponent);
  if (!vehicleSegment) return;

  let remainingVehicle = vehicleSegment;
  const yearMatch = remainingVehicle.match(/^(19\d{2}|20\d{2})(?:-|$)/);
  if (yearMatch) {
    set("year", yearMatch[1]);
    remainingVehicle = remainingVehicle.slice(yearMatch[0].length);
  }

  const bodyTypes = ["sport-utility-vehicle", "suv-crossover", "pickup-truck", "hatchback", "convertible", "minivan", "sedan", "coupe", "truck", "van", "suv"];
  const bodyType = bodyTypes.find((value) => remainingVehicle === value || remainingVehicle.endsWith(`-${value}`));
  if (bodyType) {
    set("body_type", bodyType);
    remainingVehicle = remainingVehicle.slice(0, -bodyType.length).replace(/-$/, "");
  }

  const makes = ["mercedes-benz", "aston-martin", "land-rover", "volkswagen", "mitsubishi", "chevrolet", "cadillac", "chrysler", "hyundai", "infiniti", "jaguar", "mazda", "nissan", "subaru", "toyota", "acura", "audi", "bmw", "buick", "dodge", "ford", "gmc", "honda", "jeep", "kia", "lexus", "lincoln", "ram", "volvo"];
  const make = makes.find((value) => remainingVehicle === value || remainingVehicle.startsWith(`${value}-`));
  if (make) {
    set("make", make);
    set("model", remainingVehicle.slice(make.length).replace(/^-/, ""));
  } else if (!yearMatch && !detailSegment) {
    // The established one-segment location form: /inventory/cardora-brampton
    if (vehicleSegment.toLowerCase().startsWith("cardora-")) set("location", vehicleSegment);
    else set("make", vehicleSegment);
  }

  if (!detailSegment) return;
  let remainingDetail = detailSegment;
  const vehicleTypes = ["certified-pre-owned", "used", "new"];
  const vehicleType = vehicleTypes.find((value) => remainingDetail === value || remainingDetail.startsWith(`${value}-`));
  if (vehicleType) {
    set("vehicle_type", vehicleType);
    remainingDetail = remainingDetail.slice(vehicleType.length).replace(/^-/, "");
  }

  // Locations are serialized last. Cardora locations have a stable prefix,
  // which lets us separate them even when a colour has multiple words (such
  // as "Brilliant Red") and is not in a predefined colour list.
  const cardoraLocationStart = remainingDetail.indexOf("cardora-");
  const location = cardoraLocationStart >= 0
    ? remainingDetail.slice(cardoraLocationStart).replace(/^-$/, "")
    : "";
  if (cardoraLocationStart >= 0) {
    remainingDetail = remainingDetail.slice(0, cardoraLocationStart).replace(/-$/, "");
  }

  const fuelTypes = ["gasoline-fuel", "diesel-fuel", "plug-in-hybrid", "flex-fuel", "hybrid", "electric"];
  const fuelType = fuelTypes.find((value) => remainingDetail === value || remainingDetail.endsWith(`-${value}`));
  if (fuelType) {
    set("fuel_type", fuelType);
    remainingDetail = remainingDetail === fuelType
      ? ""
      : remainingDetail.slice(0, -fuelType.length).replace(/-$/, "");
  }
  // The remaining prefix is the colour, regardless of how many words it has.
  set("exterior_color", remainingDetail);
  set("location", location);
}

export function queryValue(value: string) {
  return encodeURIComponent(value);
}

function parseQueryValue(value: string) {
  return value.replace(/--/g, "\u0000").replace(/-/g, " ").replace(/\u0000/g, "-");
}

function parseNamedQueryValue(value: string) {
  return value;
}

const COMPACT_MAKES = [
  "mercedes-benz", "aston-martin", "land-rover", "volkswagen", "mitsubishi",
  "chevrolet", "cadillac", "chrysler", "hyundai", "infiniti", "jaguar", "mazda",
  "nissan", "subaru", "toyota", "acura", "audi", "bmw", "buick", "dodge", "ford",
  "gmc", "honda", "jeep", "kia", "lexus", "lincoln", "ram", "volvo",
].map((value) => value.replace(/-/g, "--"));

const COMPACT_BODY_TYPES = [
  "sport-utility-vehicle", "suv-crossover", "pickup-truck", "hatchback", "convertible",
  "minivan", "sedan", "coupe", "truck", "van", "suv",
];

const COMPACT_TRANSMISSIONS = ["automatic", "manual", "cvt"];
const COMPACT_FUEL_TYPES = ["gasoline-fuel", "diesel-fuel", "plug-in-hybrid", "flex-fuel", "hybrid", "electric", "bev","phev"];
const COMPACT_VEHICLE_TYPES = ["certified-pre-owned", "used", "new", "as-is"];
const COMPACT_COLORS = [
  "black", "blue", "brilliant-red", "crimson-red-tin-jet", "dark-green", "ebony-twilight-metallic",
  "galaxy-silver-m", "gray", "grey", "green", "red", "silver", "white", "orange", "yellow",
  "brown", "beige", "gold", "maroon", "purple", "pearl-white", "platinum",
];

const COMPACT_FACET_VALUES: Array<readonly [string, string[]]> = [
  ["body_type", ["suv-crossover", "sport-utility-vehicle", "pickup-truck", "hatchback", "convertible", "minivan", "minivan-van", "sedan", "coupe", "truck", "van", "suv"]],
  ["transmission", COMPACT_TRANSMISSIONS],
  ["fuel_type", [
    "bev", "diesel", "electric", "electric-battery", "gasoline", "gasoline-fuel", "hev",
    "hybrid", "hybrid-gas/electric", "phev", "plug-in-hybrid", "other/don't-know",
  ]],
  ["vehicle_type", ["certified-pre-owned", "used", "new", "as-is"]],
];

const COMPACT_KNOWN_VALUES = COMPACT_FACET_VALUES.flatMap(([attribute, values]) =>
  values.map((value) => [attribute, value] as const)
);

function setCompactFilter(refinementList: PlainObject, attribute: string, value: string) {
  if (!value || refinementList[attribute]) return;
  refinementList[attribute] = [value];
}

function readRepeatedCompactFilter(token: string, refinementList: PlainObject) {
  for (const [attribute, value] of COMPACT_KNOWN_VALUES) {
    const encoded = queryValue(value).toLowerCase();
    const decoded = decodeURIComponent(encoded).toLowerCase();
    const legacySlug = value.toLowerCase().replace(/\s+/g, "-");
    const normalizedToken = token.toLowerCase();
    const isExact = normalizedToken === encoded || normalizedToken === decoded;
    const isDuplicate = normalizedToken === `${decoded}-${decoded}`
      || normalizedToken === `${encoded}-${encoded}`
      || normalizedToken === `${decoded}-${encoded}`
      || normalizedToken === `${encoded}-${decoded}`
      || normalizedToken === `${legacySlug}-${encoded}`
      || normalizedToken === `${legacySlug}-${decoded}`;
    if (isExact || isDuplicate) {
      const originalEncodedValue = isExact
        ? token
        : token.slice(-(decoded.length));
      setCompactFilter(refinementList, attribute, parseQueryValue(originalEncodedValue));
      return true;
    }
  }
  return false;
}

function readCompactFilter(value: string, refinementList: PlainObject) {
  const token = decodeURIComponent(value);
  if (!token) return;
  if (readRepeatedCompactFilter(token, refinementList)) return;

  const make = COMPACT_MAKES
    .sort((a, b) => b.length - a.length)
    .find((candidate) => token.toLowerCase() === candidate || token.toLowerCase().startsWith(`${candidate}-`));

  if (make) {
    // Keep canonical make punctuation. For example, the indexed value is
    // "Mercedes-Benz", not "Mercedes Benz".
    const parsedMake = parseQueryValue(make);
    setCompactFilter(refinementList, "make", parsedMake);
    const remaining = token.slice(make.length).replace(/^-/, "");
    if (remaining) {
      const yearIndex = remaining.search(/(?:^|-)(19\d{2}|20\d{2})(?:-|$)/);
      if (yearIndex > 0) {
        const model = remaining.slice(0, yearIndex).replace(/-$/, "");
        setCompactFilter(refinementList, "model", parseQueryValue(model));
        const yearAndRemainder = remaining.slice(yearIndex).replace(/^-/, "");
        const yearMatch = yearAndRemainder.match(/^(19\d{2}|20\d{2})(?:-(.*))?$/);
        if (yearMatch) {
          setCompactFilter(refinementList, "year", yearMatch[1]);
          if (yearMatch[2]) readCompactFilter(yearMatch[2], refinementList);
        }
      } else {
        const color = COMPACT_COLORS
          .sort((a, b) => b.length - a.length)
          .find((candidate) => remaining.toLowerCase().endsWith(`-${candidate}`));
        if (color) {
          const model = remaining.slice(0, -(color.length + 1));
          setCompactFilter(refinementList, "model", parseQueryValue(model));
          setCompactFilter(refinementList, "exterior_color", titleCase(parseQueryValue(color)));
        } else {
          setCompactFilter(refinementList, "model", parseQueryValue(remaining));
        }
      }
    }
    return;
  }

  const year = token.match(/^(19\d{2}|20\d{2})(?:-|$)/);
  if (year) {
    setCompactFilter(refinementList, "year", year[1]);
    const remainder = token.slice(year[0].length);
    if (remainder) readCompactFilter(remainder, refinementList);
    return;
  }

  const normalized = token.toLowerCase();
  const locationIndex = normalized.indexOf("-cardora-");
  if (normalized.startsWith("cardora-")) {
    setCompactFilter(refinementList, "location", parseQueryValue(token));
  } else if (locationIndex > 0) {
    setCompactFilter(refinementList, "location", parseQueryValue(token.slice(locationIndex + 1)));
    setCompactFilter(refinementList, "exterior_color", titleCase(parseQueryValue(token.slice(0, locationIndex))));
  } else if (COMPACT_VEHICLE_TYPES.some((vehicleType) => normalized === vehicleType || normalized.endsWith(`-${vehicleType}`))) {
    const vehicleType = COMPACT_VEHICLE_TYPES.find((candidate) => normalized === candidate || normalized.endsWith(`-${candidate}`));
    if (vehicleType) setCompactFilter(refinementList, "vehicle_type", parseQueryValue(vehicleType));
    const color = token.slice(0, -(vehicleType?.length || 0)).replace(/-$/, "");
    if (color) setCompactFilter(refinementList, "exterior_color", titleCase(parseQueryValue(color)));
  } else if (COMPACT_BODY_TYPES.some((bodyType) => normalized === bodyType || normalized.endsWith(`-${bodyType}`))) {
    const bodyType = COMPACT_BODY_TYPES.find((candidate) => normalized === candidate || normalized.endsWith(`-${candidate}`));
    if (bodyType) setCompactFilter(refinementList, "body_type", parseQueryValue(bodyType));
    const color = token.slice(0, -(bodyType?.length || 0)).replace(/-$/, "");
    if (color) setCompactFilter(refinementList, "exterior_color", titleCase(parseQueryValue(color)));
  } else if (COMPACT_TRANSMISSIONS.some((transmission) => normalized === transmission || normalized.endsWith(`-${transmission}`))) {
    const transmission = COMPACT_TRANSMISSIONS.find((candidate) => normalized === candidate || normalized.endsWith(`-${candidate}`));
    if (transmission) setCompactFilter(refinementList, "transmission", parseQueryValue(transmission));
    const color = token.slice(0, -(transmission?.length || 0)).replace(/-$/, "");
    if (color) setCompactFilter(refinementList, "exterior_color", titleCase(parseQueryValue(color)));
  } else if (COMPACT_FUEL_TYPES.some((fuelType) => normalized === fuelType || normalized.endsWith(`-${fuelType}`))) {
    const fuelType = COMPACT_FUEL_TYPES.find((candidate) => normalized === candidate || normalized.endsWith(`-${candidate}`));
    if (fuelType) setCompactFilter(refinementList, "fuel_type", parseQueryValue(fuelType));
    const color = token.slice(0, -(fuelType?.length || 0)).replace(/-$/, "");
    if (color) setCompactFilter(refinementList, "exterior_color", parseQueryValue(color));
  } else if (COMPACT_BODY_TYPES.includes(normalized)) {
    setCompactFilter(refinementList, "body_type", parseQueryValue(token));
  } else {
    setCompactFilter(refinementList, "exterior_color", titleCase(parseQueryValue(token)));
  }
}

function getRangeBounds(value: unknown): [unknown, unknown] {
  if (Array.isArray(value)) return [value[0], value[1]];
  if (typeof value === "string") {
    const [low = "", high = ""] = value.split(":", 2);
    return [low, high];
  }
  return [undefined, undefined];
}

function getPathFilters(route: PlainObject): PathFilters {
  const filters: PathFilters = {};
  PATH_ATTRIBUTES.forEach((attribute) => {
    const values = route.refinementList?.[attribute] || [];
    if (values.length === 1) filters[attribute] = values;
  });
  if (filters.model && !filters.make) delete filters.model;
  return filters;
}

function serializePublicUrl(route: PlainObject) {
  const params: string[] = [];
  const sourceRefinementList = route.refinementList || {};
  const refinementList: PlainObject = {};

  Object.entries(sourceRefinementList).forEach(([attribute, values]) => {
    if (!Array.isArray(values)) return;
    refinementList[attribute] = [...new Set(values.map(String))];
  });

  // A compact token can be misread as a model when it is a body, fuel, or
  // vehicle value containing hyphens. Do not serialize that duplicate model.
  const nonModelFacetValues = new Set([
    ...(refinementList.body_type || []),
    ...(refinementList.vehicle_type || []),
    ...(refinementList.fuel_type || []),
    ...(refinementList.transmission || []),
  ].map((value: string) => value.toLowerCase()));
  if (Array.isArray(refinementList.model)) {
    refinementList.model = refinementList.model.filter(
      (model: string) => !nonModelFacetValues.has(model.toLowerCase())
    );
  }
  const selectedMakes = new Set<string>(refinementList.make || []);
  
  const appendFacet = (attribute: string) => {
    const values: string[] = route.refinementList?.[attribute] || [];
    if (!values.length) return;

    let serializedValues: string[];
    if (attribute === "model") {
      serializedValues = values
        .map((model) => {
          const make = modelMakeAssociations.get(model) || getModelMakeMap().get(model);
          return make && selectedMakes.has(make) ? `${queryValue(make)};${queryValue(model)}` : null;
        })
        .filter((value): value is string => value !== null);
      // If no valid models remain, don't add the parameter at all
      if (!serializedValues.length) return;
    } else {
      serializedValues = values.map(queryValue);
    }
    
    params.push(`${FILTER_KEYS[attribute]}=${serializedValues.join(",")}`);
  };
  const appendRange = (attribute: keyof typeof RANGE_KEYS, index: 0 | 1) => {
    const [low, high] = getRangeBounds(route.range?.[attribute]);
    const value = index === 0 ? low : high;
    if (value !== undefined && value !== "") {
      params.push(`${RANGE_KEYS[attribute][index]}=${encodeURIComponent(String(value))}`);
    }
  };

  // Canonical query order — always serialized in this exact sequence,
  // regardless of the order in which the user selected the filters.
  // 1. makes  2. models  3. year  4. priceLow  5. locations
  // 6. colors  7. bodyTypes  8. transmissions  9. fuelTypes
  // 10. odometerLow  11. vehicleTypes  12. priceHigh  13. odometerHigh
  appendFacet("make");
  appendFacet("model");
  appendFacet("year");
  appendRange("selling_price", 0);   // priceLow
  appendFacet("location");
  appendFacet("exterior_color");
  appendFacet("body_type");
  appendFacet("transmission");
  appendFacet("fuel_type");
  appendRange("odometer", 0);        // odometerLow
  appendFacet("vehicle_type");
  appendRange("selling_price", 1);   // priceHigh
  appendRange("odometer", 1);        // odometerHigh
  if (route.query) params.push(`q=${encodeURIComponent(route.query)}`);
  const sort = getPublicSort(route.sortBy);
  if (sort) {
    // field/direction are always safe internal identifiers (letters, digits,
    // underscores) and ':' / ',' are valid unencoded in a query string, so
    // this is left un-percent-encoded for a readable URL.
    params.push(`sortBy=status_rank:asc,${sort.field}:${sort.direction.toLowerCase()}`);
  }

  // Canonical URLs always use named parameters. This keeps make/model hyphens
  // literal and prevents filter boundaries from becoming ambiguous.
  const path = "/inventory";
  return params.length ? `${path}?${params.join("&")}` : path;
}

function readRouteState(): PlainObject {
  if (typeof window === "undefined") return {};

  const params = new URLSearchParams(window.location.search);
  const refinementList: PlainObject = {};
  const range: PlainObject = {};
  
  for (const [attribute, key] of Object.entries(FILTER_KEYS)) {
    const value = params.get(key);
    if (!value) continue;

    if (attribute === "model") {
      const models: string[] = [];
      const impliedMakes: string[] = [];
      value.split(",").filter(Boolean).forEach((entry) => {
        const [rawMake, rawModel] = entry.includes(";") ? entry.split(";", 2) : [undefined, entry];
        const model = parseNamedQueryValue(rawModel);
        models.push(model);
        if (rawMake) {
          const make = parseNamedQueryValue(rawMake);
          impliedMakes.push(make);
          modelMakeAssociations.set(model, make);
          setModelMakeMap([[model, make]]);
        }
      });
      refinementList.model = models;
      if (impliedMakes.length) {
        const existingMakes: string[] = refinementList.make || [];
        refinementList.make = [...new Set([...existingMakes, ...impliedMakes])];
      }
      continue;
    }

    refinementList[attribute] = value.split(",").filter(Boolean).map(parseNamedQueryValue);
  }

  const namedKeys = new Set([
    ...Object.values(FILTER_KEYS),
    ...Object.values(RANGE_KEYS).flat(),
    "q",
    "sortBy",
    "sortField",
    "sortDirection",
    "sort",
  ]);
  for (const [key, value] of params.entries()) {
    // A compact filter is intentionally represented as a query key without
    // an equals sign, for example ?black or ?BMW-3--Series.
    if (!namedKeys.has(key) && value === "") {
      readCompactFilter(key, refinementList);
    }
  }

  Object.keys(refinementList).forEach((attribute) => {
    if (Array.isArray(refinementList[attribute])) {
      refinementList[attribute] = [...new Set(refinementList[attribute])];
    }
  });

  const nonModelFacetValues = new Set([
    ...(refinementList.body_type || []),
    ...(refinementList.vehicle_type || []),
    ...(refinementList.fuel_type || []),
    ...(refinementList.transmission || []),
  ].map((value: string) => value.toLowerCase()));
  if (Array.isArray(refinementList.model)) {
    refinementList.model = refinementList.model.filter(
      (model: string) => !nonModelFacetValues.has(model.toLowerCase())
    );
    if (refinementList.model.length === 0) delete refinementList.model;
  }

  for (const [attribute, [lowKey, highKey]] of Object.entries(RANGE_KEYS)) {
    const low = params.get(lowKey);
    const high = params.get(highKey);
    if (low !== null || high !== null) {
      // React InstantSearch stores a range as "low:high".
      range[attribute] = `${low || ""}:${high || ""}`;
    }
  }

  const route: PlainObject = { refinementList, range };
  
  const query = params.get("q");
  if (query) route.query = query;

  // Current format: a single sortBy param carrying the full criteria list,
  // including status_rank, e.g. "status_rank:asc,price:asc".
  const sortByParam = params.get("sortBy");
  // Legacy formats, still accepted so previously shared links keep working.
  const legacySortField = params.get("sortField");
  const legacySortDirection = params.get("sortDirection")?.toUpperCase();
  const legacySort = params.get("sort");

  if (sortByParam) {
    const criteria = sortByParam.split(",").filter(Boolean);
    const primaryCriterion = criteria.find((c) => !c.startsWith("status_rank:")) || criteria[0];
    const [field, direction] = primaryCriterion?.split(":", 2) ?? [];
    if (field && direction && (direction.toUpperCase() === "ASC" || direction.toUpperCase() === "DESC")) {
      route.sortField = field;
      route.sortDirection = direction.toUpperCase();
    }
  } else if (legacySortField && (legacySortDirection === "ASC" || legacySortDirection === "DESC")) {
    route.sortField = legacySortField;
    route.sortDirection = legacySortDirection;
  } else if (legacySort) {
    route.sortBy = legacySort;
  }
 
  const pathFilters = window.history.state?.__inventoryPathFilters as PathFilters | undefined;
  if (pathFilters && window.location.pathname.startsWith("/inventory/")) {
    PATH_ATTRIBUTES.forEach((attribute) => {
      if (pathFilters[attribute]?.length) refinementList[attribute] = pathFilters[attribute];
    });
  }

  // A fresh request has no history state. Decode the canonical path values
  // for any refinements not already supplied in the (non-path) query string.
  const segments = window.location.pathname.replace(/^\/inventory\/?/, "").split("/").filter(Boolean);
  if (!pathFilters && isInventoryListingPath(window.location.pathname)) {
    readPathOnlyFilters(segments, refinementList);
  }

  return route;
}

export const createInventoryStateMapping = (config: AppConfig) => {
  const indexName = config.site.collection || "";
  const defaultSort = `${indexName}/sort/status_rank:asc,created_at:desc`;

  return {
    stateToRoute(uiState: UiState) {
      const state = uiState[indexName] || {};
      return {
        query: state.query || undefined,
        refinementList: state.refinementList || {},
        range: state.range || {},
        sortBy: state.sortBy && state.sortBy !== defaultSort ? state.sortBy : undefined,
      };
    },

    routeToState(routeState: PlainObject | undefined | null) {
      const route = routeState || {};
      const sortBy = route.sortField && (route.sortDirection === "ASC" || route.sortDirection === "DESC")
        ? `${indexName}/sort/status_rank:asc,${getInternalSortField(route.sortField)}:${route.sortDirection.toLowerCase()}`
        : route.sortBy || defaultSort;
      return {
        [indexName]: {
          query: route.query || "",
          refinementList: route.refinementList || {},
          range: route.range || {},
          sortBy,
        },
      };
    },
  };
};

export function createInventoryRouter(_config: AppConfig) {
  watchExternalUrlChanges();
  let callback: ((route: PlainObject) => void) | null = null;
  const initialRoute = readRouteState();
  let previousRoute = initialRoute;
  let pathFilters: PathFilters =
    typeof window !== "undefined"
      ? window.history.state?.__inventoryPathFilters || getPathFilters(initialRoute)
      : {};

  // Tracks the last URL we actually wrote via history.replaceState, so we can
  // skip no-op writes below. See performWrite for why this matters.
  let lastWrittenUrl: string | null = null;

  if (typeof window !== "undefined" && Object.keys(pathFilters).length && window.location.pathname === "/inventory") {
    const bootstrapUrl = serializePublicUrl(initialRoute);
    isInternalUrlWrite = true;
    window.history.replaceState({ ...initialRoute, __inventoryPathFilters: pathFilters }, "", bootstrapUrl);
    isInternalUrlWrite = false;
    lastWrittenUrl = bootstrapUrl;
  }

  const performWrite = (route: PlainObject, filters: PathFilters) => {
    if (typeof window === "undefined") return;
    if (!isInventoryListingPath(window.location.pathname)) return;

    const url = serializePublicUrl(route);

    if (url === lastWrittenUrl) return;
    lastWrittenUrl = url;

    const state = { ...route, __inventoryPathFilters: filters };

    // Safari often jumps scroll UP on history.replaceState. Only correct
    // upward jumps so bottom infinite-scroll growth is not fought.
    const scrollY = window.scrollY;
    isInternalUrlWrite = true;
    window.history.replaceState(state, "", url);
    isInternalUrlWrite = false;
    if (window.scrollY < scrollY - 1) {
      window.scrollTo(0, scrollY);
    }
  };

  const resync = () => performWrite(previousRoute, pathFilters);
  activeRouterResync = resync;

  const notify = () => {
    if (!isInventoryListingPath(window.location.pathname)) return;
    const route = readRouteState();
    previousRoute = route;
    if (window.location.pathname === "/inventory") {
      pathFilters = getPathFilters(route);
    }
    callback?.(route);
  };
  externalUrlListeners.add(notify);

  return {
    read: readRouteState,

    write(nextRoute: PlainObject) {
      pathFilters = getPathFilters(nextRoute);
      previousRoute = nextRoute;
      performWrite(nextRoute, pathFilters);
    },

    resync,

    createURL(routeState: PlainObject) {
      // InstantSearch only uses this for links; write() is the canonical serializer.
      const query = routeState.query ? `?q=${encodeURIComponent(routeState.query)}` : "";
      return `${window.location.origin}/inventory${query}`;
    },

    onUpdate(nextCallback: (route: PlainObject) => void) {
      callback = nextCallback;
    },

    dispose() {
      externalUrlListeners.delete(notify);
      if (activeRouterResync === resync) activeRouterResync = null;
      callback = null;
    },
  };
}